#keycloak:
#  auth-server-url: https://localhost:8080/auth
#  realm: testrealm
#  resource: testclient
#  public-client: true
#  principal-attribute: preferred_username
#
#  security-constraints:
#    - authRoles:
#        - user
#      securityCollections:
#        - patterns:
#            - "/secured/*"
spring:
  security:
    oauth2:
      resourceserver:
        multitenant:
          enabled: true
          resolve-mode: jwt
          jwt:
            authorities-converter: io.quantics.multitenant.oauth2.config.KeycloakRealmAuthoritiesConverter
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update


server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web: TRACE

