spring:
  security:
    oauth2:
      resourceserver:
        multitenant:
          enabled: true
          resolve-mode: jwt
          jwt:
            authorities-converter: io.quantics.multitenant.oauth2.config.KeycloakRealmAuthoritiesConverter
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

project:
  name: /springarchetype
server:
  port: 8081
